### ISSUE TITLE
Add a secrets/config mechanism for the apikey

### ISSUE THREAD

**Issue by stephlocke** [DoubleYouGTT/hubspot#1]
Currently, API keys are plaintext arguments to functions. This isn't great, we should enable folks to store these like other important credentials e.g. [tic](https://github.com/ropenscilabs/tic).

**Comment by maelle** [comment]
* Only putting them in .Renviron

* Or look into https://github.com/r-lib/keyring#readme (h/t @stephlocke )

**Comment by maelle** [comment]
https://github.com/khufkens/ecmwfr/search?q=keyring&unscoped_q=keyring

https://github.com/ThinkR-open/togglr/search?utf8=%E2%9C%93&q=keyring&type=

**Comment by stephlocke** [comment]
I have no strong preference on solution here. Happy to go with what you think best :)

**Comment by maelle** [comment]
Should there be a message when we use the demo key :thinking:

**Comment by stephlocke** [comment]
I don't think that would add much benefit relative to the work needed to implement and maintain it

**Comment by maelle** [comment]
in the PR from yesterday I think there's a message
