### ISSUE TITLE
Do not import whole packages?

### ISSUE THREAD

**Issue by maelle** [DoubleYouGTT/hubspot#11]
At the moment

```r
#' @import purrr
#' @import dplyr
#' @import tidyr
```

**Comment by stephlocke** [comment]
We were using so much from the packages that life was easier to do this whilst getting to grips with the range of functionality needed. I recommend switching to be more specific once the package is more mature to save needing to edit this regularly.

**Comment by maelle** [comment]
When we do, we can use tools that help automate the namespacing.
