### ISSUE TITLE
Add oauth mechanism for hubspot access

### ISSUE THREAD

**Issue by stephlocke** [DoubleYouGTT/hubspot#2]
As well as #1 enabling better storage of API keys we should also enable [oauth access](https://developers.hubspot.com/docs/methods/auth/oauth-overview).

**Comment by maelle** [comment]
Should we even _enforce_ OAuth? Cf https://github.com/lockedata/hubspot/issues/14#issuecomment-544375697

**Comment by maelle** [comment]
in https://developers.hubspot.com/docs/methods/auth/oauth-overview

"HubSpot's APIs allow for two means of authentication, OAuth and API keys.  API keys are great for rapid prototyping, but for security and commercial use, all integrations designed to be used by multiple HubSpot customers should use OAuth - this is required for becoming a featured integration."

**Comment by maelle** [comment]
"OAuth access tokens will expire after a certain period of time. This is to make sure that if they are compromised, attackers will only have access for a short period. The token's lifespan is specified in the expires_in field when an authorization code is exchanged for an access token, which is 6 hours by default."

**Comment by stephlocke** [comment]
I don't want to enforce oauth because a lot of clients etc implementing this benefit from the stability and ease of implementation that comes from using their API key. I'd rather it be the preferred but non-mandatory option.

**Comment by maelle** [comment]
Thinking about how to make it optional. 

Inspiration links.

https://cran.r-project.org/web/packages/gargle/vignettes/get-api-credentials.html#api-key

**Comment by maelle** [comment]
https://github.com/tidyverse/googledrive/blob/master/R/request_generate.R

**Comment by maelle** [comment]
Need to define order of priority in the case in which both key and token are present.

How to pass key. I'd say param in all functions + keyring.
How to pass token. Param as well (path to token) + token location in a variable in .Renviron, à la rtweet. 

https://github.com/ropensci/rtweet/blob/1bd1e16d14df8b31a13a8c2f0e0ff0e87ea066d1/R/tokens.R#L220

**Comment by maelle** [comment]
I didn't know about https://cran.r-project.org/web/packages/httr/vignettes/secrets.html

**Comment by maelle** [comment]
Other notes
- Do we want the users to be able to provide their own app
- Do we want flexibility on the scopes provided

**Comment by maelle** [comment]
I'm quite new to this app stuff, I hope I'm not being stupid by wanting to hardcode our client ID and "secret". I read "Surprisingly, the “client secret” in an oauth_app() is not a secret. " in https://httr.r-lib.org/articles/secrets.html#introduction

**Comment by maelle** [comment]
Currently in the app I'm creating for choosing scopes I used the scope info I had webscraped for the methods that we plan to support one day. Therefore we needed contacts, content, forms, e-commerce, tickets.

**Comment by maelle** [comment]
Summary of my questions
- Is it fine to publish our client secret and ID
- Is the current scope selection fine (I'd prefer to only have reading scopes, but for tickets for instance, it's read and write or nothing)
- Should the user be able to bring their own app (e.g. to use different scopes)
- In the presence of both a key and a token, what do we prioritize
- Do we expect the user to have only one token or should we handle the case where there is one token by project (e.g. if you have several HubSpot accounts)

**Comment by maelle** [comment]
TODOS:
* Infrastructure based on decisions above
* Function for creating the token and saving it
* Look into _refreshing_ tokens

**Comment by stephlocke** [comment]
rtweet is a good example of an oauth auth package (imo anyways!) https://github.com/ropensci/rtweet/blob/master/R/bearer_token.R

**Comment by stephlocke** [comment]
1. Yes, I think it's fine to publish but check rtweet
1. Minimal permissions is desirable so read only where available
1. No need for alt apps at this stage
1. Prioritse a token - altho make it switchable?
1. Have a default search and storage  location for the oauth but enable it to be amended

**Comment by maelle** [comment]
1. in rtweet there's no default app, I need to understand gargle better I guess.

**Comment by maelle** [comment]
* I need to work on a function for creating and storing the token (like what rtweet does). Once that is done, the default value of token_path should be Sys.getenv("HUBSPOT_TOKEN_PATH").

* Reg scope, all tests need to be run with OAuth to ensure the scopes of the app are sufficient for that. I'm still unsure how having a single app for everything will work, will the user think there are too many scopes.

* I need to understand refresh.

What I have understood

* The secret is not secret, yay.

* How to pass the token to GET.

 * I have drafted a function that makes a decision based on token_path and apikey values.

**Comment by maelle** [comment]
But do we actually want to run all tests twice (once with OAuth once with API key)?! Probably all with OAuth, a few with API keys should be enough.

**Comment by stephlocke** [comment]
I'd probably do the converse for CRAN as the key means never having to change a file system ;)

**Comment by maelle** [comment]
Right, so maybe OAuth for all tests in one Travis build.

**Comment by stephlocke** [comment]
yep

**Comment by maelle** [comment]
closed via #48
