### ISSUE TITLE
Do we need an API version argument for some functions?

### ISSUE THREAD

**Issue by maelle** [DoubleYouGTT/hubspot#23]
I see some v1 in the docs, some v2 in the code.

**Comment by stephlocke** [comment]
It looks like they don't retain docs for version 1 of APIs so it's possible they don't maintain the endpoints either. I would keep maintaining versions as an internal part of the package, versus an explicit option.

**Comment by maelle** [comment]
I don't understand your comment, do you mean that when v2 of an endpoint exists, v1 of that endpoint disappears?

**Comment by stephlocke** [comment]
as far as i can tell! I haven't seen an increment occur but with no docs for v1 support, it seems likely

**Comment by maelle** [comment]
Ok so inside the package, for each method we'll use whatever version works. Thank you!
