### ISSUE TITLE
get_companies returns nothing

### ISSUE THREAD

**Issue by maelle** [DoubleYouGTT/hubspot#32]
not caught by tests though

```r
library("hubspot")
get_companies()
companies <- get_companies()
companies
```

**Comment by maelle** [comment]
(`companies` is something)

**Comment by stephlocke** [comment]
Returns lots of records for me 🤔 
Perhaps we get 0 results when it's been ratelimited or something?

**Comment by maelle** [comment]
I mean the function itself has no return inside it.

Why use the set names thing?

**Comment by stephlocke** [comment]
Ah, as I was only interested in the companies cleaned up I hadn't noticed it was returning invisibly when called standalone. `hubspot::company_properties()` works fine :) 

Add `return(companies)` to make the invisible visible 
https://github.com/lockedata/hubspot/blob/84e9c3442fd3acc8eb4d764534fb0f4e1f0b5bfc/R/get_companies.R#L57
