### ISSUE TITLE
R files

### ISSUE THREAD

**Issue by maelle** [DoubleYouGTT/hubspot#33]
I wonder whether there should be one R script by entity.

**Comment by maelle** [comment]
At least for the getters.

For the mungers, I'm not sure how to order them, but I think the filename should not start by a verb, this way the alphabetical order would be more informative.

**Comment by stephlocke** [comment]
👍

**Comment by maelle** [comment]
depends on #36

**Comment by maelle** [comment]
with the current renaming work, I'm going for a file by endpoint.
