### ISSUE TITLE
Rename & reorganize all functions like hs_deals_raw() and hs_deals_tidy()

### ISSUE THREAD

**Issue by maelle** [DoubleYouGTT/hubspot#36]
How do we name raw getters and functions returning tidy output?

One solution by Steph

```r
raw_deals<-raw_all_deals()
deal_props <- tidy_all_deals(raw_deals, view = "property_versions")
deal_associations <- tidy_all_deals(raw_deals, view = associations")
```

Seeing that I'm wondering whether all raw getters should return a R6 object that's not much different from a list except it has tidy() methods that depends on the function that created it. But maybe `get_deals()$view("associations")` is _not_ an intuitive syntax. It could also be `get_deals()$associations()` or so to take more advantage of tab-autocompletion.

**Comment by maelle** [comment]
If the output of raw getters were an R6 object, the default print method should show what function created it (maybe what params except for the key!), the URL to docs of the endpoint.

**Comment by maelle** [comment]
The R6 idea is really growing on me. :thinking: 

Then there'd be one R script for each category with the getter + the methods (print method, different tidying functions).

**Comment by maelle** [comment]
The scaffolding of R files will depend on this.

**Comment by stephlocke** [comment]
I'm not sure I like the R6 method. But thinking required!

My initial issues / worries are:
- the fields returned by the hubspot api aren't stable. I tend to think of R6 as great for well-known schema so you can add type safety etc
- it adds an unusual API to the package that diverges from current trends.

**Comment by maelle** [comment]
What I liked with R6 was the autocompletion this way the user could know what tidying method is available for each raw thing.

**Comment by maelle** [comment]
I still like the R6 idea because I'm worried it might be complicated for the user to know what arguments to pass to what tidiers.

**Comment by maelle** [comment]
|file                        |from                    |to                              |type | line1| line2| col1| col2|str                    |
|:---------------------------|:-----------------------|:-------------------------------|:----|-----:|-----:|----:|----:|:----------------------|
|R/company_properties.R      |company_properties      |hubspot::get_companies          |call |    10|    10|   44|   56|get_companies          |
|R/get_companies.R           |get_companies           |hubspot::get_company_properties |call |    19|    19|   40|   61|get_company_properties |
|R/get_contacts.R            |get_contacts            |hubspot::get_contact_properties |call |    22|    22|   40|   61|get_contact_properties |
|R/contact_properties.R      |contact_properties      |hubspot::get_contacts           |call |    10|    10|   43|   54|get_contacts           |
|R/deal_pipeline_stages.R    |deal_pipeline_stages    |hubspot::get_deal_pipelines     |call |    10|    10|   46|   63|get_deal_pipelines     |
|R/deal_pipelines.R          |deal_pipelines          |hubspot::get_deal_pipelines     |call |    10|    10|   40|   57|get_deal_pipelines     |
|R/get_deals.R               |get_deals               |hubspot::get_deal_properties    |call |    13|    13|   36|   54|get_deal_properties    |
|R/deal_associations.R       |deal_associations       |hubspot::get_deals              |call |    10|    10|   39|   47|get_deals              |
|R/deal_properties.R         |deal_properties         |hubspot::get_deals              |call |    10|    10|   37|   45|get_deals              |
|R/deal_properties_history.R |deal_properties_history |hubspot::get_deals              |call |    10|    10|   45|   53|get_deals              |
|R/deal_stages_history.R     |deal_stages_history     |hubspot::get_deals              |call |    10|    10|   41|   49|get_deals              |
|R/owners.R                  |owners                  |hubspot::get_owners             |call |    10|    10|   29|   38|get_owners             |
|R/get_companies.R           |get_companies           |hubspot::hubspot_key_get        |call |    18|    18|   36|   50|hubspot_key_get        |
|R/get_company_properties.R  |get_company_properties  |hubspot::hubspot_key_get        |call |    10|    10|   45|   59|hubspot_key_get        |
|R/get_contacts.R            |get_contacts            |hubspot::hubspot_key_get        |call |    21|    21|   35|   49|hubspot_key_get        |
|R/get_contacts_properties.R |get_contact_properties  |hubspot::hubspot_key_get        |call |    10|    10|   45|   59|hubspot_key_get        |
|R/get_deal_pipelines.R      |get_deal_pipelines      |hubspot::hubspot_key_get        |call |    11|    11|   41|   55|hubspot_key_get        |
|R/get_deal_properties.R     |get_deal_properties     |hubspot::hubspot_key_get        |call |    10|    10|   42|   56|hubspot_key_get        |
|R/get_deals.R               |get_deals               |hubspot::hubspot_key_get        |call |    12|    12|   32|   46|hubspot_key_get        |
|R/get_owners.R              |get_owners              |hubspot::hubspot_key_get        |call |    20|    20|   33|   47|hubspot_key_get        |

Obtained by

```r
map <- pkgapi::map_package()
calls <- map$calls[map$calls$from %in% map$exports &
                     map$calls$to %in% paste0("hubspot::",
                                                map$exports),]
calls <- dplyr::arrange(calls, to)
```

**Comment by stephlocke** [comment]
Happy with the proposed naming scheme changes

**Comment by maelle** [comment]
you mean R6 or your own idea with tidy_?

**Comment by stephlocke** [comment]
I misconstrued what the table was about I guess. I'm still not sure about R6 and in the event of a deadlock like this I go to twitter so I'll get back to you in a day or so with the results

**Comment by maelle** [comment]
:four_leaf_clover:

**Comment by maelle** [comment]
Ping @stephlocke :slightly_smiling_face:

**Comment by stephlocke** [comment]
polling now -> https://twitter.com/TheStephLocke/status/1197639424659603456

**Comment by stephlocke** [comment]
survey says... switchable tidiers
To ensure these work effectively, they could be unexported standalone tidiers that get called based on the switches. That way we can have hideously long descriptive names for them but not subject anyone to them.

**Comment by maelle** [comment]
cf #58

**Comment by maelle** [comment]
Once the renaming is all done

- [ ] Update NEWs

- [ ] Update the README

- [ ] Update CONTRIBUTING

- [ ] Open issue planning to make functions *defunct*

And then on to scaffolding!
