### ISSUE TITLE
LDify the repo

### ISSUE THREAD

**Issue by stephlocke** [DoubleYouGTT/hubspot#5]
Make sure the repo has all the right labels etc 

Check repos like [HIBPwned](https://github.com/lockedata/HIBPwned) to see what's what, read [Harmonising and emojifying our github repos](https://itsalocke.com/blog/harmonizing-and-emojifying-our-github-issue-trackers/), and when in doubt consult with @maelle!

**Comment by sgetalbo** [comment]
👋 @stephlocke Did this and the other issue you assigned me get workstream tasks? I think these were created when the git issue bot went on his Christmas break? I will create if needs be just to keep me up to speed with my tasks!

**Comment by stephlocke** [comment]
@sgetalbo , yeah please create the task on workstreams :)

**Comment by maelle** [comment]
For labels I am installing https://github.com/lockedata/lockedev

**Comment by maelle** [comment]
There's no meta label in lockedev but I felt we needed one here. :wink:
