### ISSUE TITLE
is lintr-bot really a good thing

### ISSUE THREAD

**Issue by maelle** [DoubleYouGTT/hubspot#52]
In particular, why does it comment several times on each problematic commit.

**Comment by jonmcalder** [comment]
I find lintr-bot a little noisy, and prefer to check (or even enforce) certain linting rules before pushing commits using [pre-commit](https://github.com/lorenzwalthert/precommit) hooks.

The downside is that contributors - especially new ones - likely won't (or won't want to) embrace the overhead / complexity of a pre-commit hook, so maybe there would need to be some later / downstream CI pipeline to ensure linting does eventually or occasionally take place (if it's really a priority), but the upside is one doesn't get spammed by lintr-bot in in pull requests 😁

Disclaimer: I contributed the initial `lintr` integration for [precommit](https://github.com/lorenzwalthert/precommit).

**Comment by maelle** [comment]
Do you know I made the avatat for lintr-bot? It prevents me from hating it 😂

**Comment by maelle** [comment]
@stephlocke could we remove the lintr bot and add a (vanilla/precommit) pre-commit styler hook?

**Comment by maelle** [comment]
I am really in favour of a hook.

**Comment by stephlocke** [comment]
Sure. tbh I don't remember how I added it, or why it seems to post so many times :)

**Comment by maelle** [comment]
I'm running a styler pre-commit hook locally, it takes a little while, if we switch to precommit I think we could have it run on edited files only @jonmcalder?

**Comment by maelle** [comment]
Btw lintr-bot spammed the repo because the lintr stuff was run on all 4 Travis builds... entirely my fault.
