### ISSUE TITLE
Extend getOwners.R with includeInactive property

### ISSUE THREAD

**Issue by edwardpearson** [DoubleYouGTT/hubspot#8]
When a user (owner) is deactivated in HubSpot they are not removed from deals as the owner.  This can cause downstream issues.  It would be useful to be able to set the "includeInactive" property on the hubspot api call (owners/v2/owners) when calling getOwners.

**Comment by maelle** [comment]
API docs https://developers.hubspot.com/docs/methods/owners/get_owners

What's missing at the moment is the possibility to use the "optional parameters", includeInactive and email.

**Comment by maelle** [comment]
Working on this #44 . Note that includeInactive filters on the remotes list, not on the fact an owner is active, so I'm not sure it's what you were after (but that's what the API provides). :confused:

``` r
library("hubspot")
all_owners <- get_owners()
#> Could not find Hubspot API key, will use the 'demo' key.
#> Please run hubspot_key_set() to set your API key.
active_owners <- get_owners(include_inactive = FALSE)
#> Could not find Hubspot API key, will use the 'demo' key.
#> Please run hubspot_key_set() to set your API key.

any(!purrr::map_lgl(active_owners, "isActive"))
#> [1] TRUE
any(lengths(purrr::map(active_owners, "remoteList")) == 0)
#> [1] FALSE
any(lengths(purrr::map(all_owners, "remoteList")) == 0)
#> [1] TRUE
```

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

To remove inactive users based in isActive, you'd need to filter the output, e.g.:

```r
all_owners[purrr::map_lgl(active_owners, "isActive")]
```
